/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export { VRFV2WrapperConsumerBase__factory } from "./VRFV2WrapperConsumerBase__factory";
